// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRole represents the type of agent in the A2A recruitment system
type AgentRole int32

const (
	AgentRole_AGENT_ROLE_UNSPECIFIED AgentRole = 0
	AgentRole_SEEKER                 AgentRole = 1
	AgentRole_RECRUITER              AgentRole = 2
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "AGENT_ROLE_UNSPECIFIED",
		1: "SEEKER",
		2: "RECRUITER",
	}
	AgentRole_value = map[string]int32{
		"AGENT_ROLE_UNSPECIFIED": 0,
		"SEEKER":                 1,
		"RECRUITER":              2,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// AgentState represents the current state of an agent in the FSM
type AgentState int32

const (
	AgentState_AGENT_STATE_UNSPECIFIED AgentState = 0
	AgentState_IDLE                    AgentState = 1
	AgentState_SEARCHING               AgentState = 2
	AgentState_NEGOTIATING             AgentState = 3
	AgentState_INTERVIEWING            AgentState = 4
	AgentState_OFFER_RECEIVED          AgentState = 5
	AgentState_HIRED                   AgentState = 6
	AgentState_REJECTED                AgentState = 7
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "IDLE",
		2: "SEARCHING",
		3: "NEGOTIATING",
		4: "INTERVIEWING",
		5: "OFFER_RECEIVED",
		6: "HIRED",
		7: "REJECTED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED": 0,
		"IDLE":                    1,
		"SEARCHING":               2,
		"NEGOTIATING":             3,
		"INTERVIEWING":            4,
		"OFFER_RECEIVED":          5,
		"HIRED":                   6,
		"REJECTED":                7,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// TaskPriority for RabbitMQ queue tasks
type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_LOW                       TaskPriority = 1
	TaskPriority_NORMAL                    TaskPriority = 2
	TaskPriority_HIGH                      TaskPriority = 3
	TaskPriority_CRITICAL                  TaskPriority = 4
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "NORMAL",
		3: "HIGH",
		4: "CRITICAL",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"LOW":                       1,
		"NORMAL":                    2,
		"HIGH":                      3,
		"CRITICAL":                  4,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

// InterviewFormat for interview invitations
type InterviewFormat int32

const (
	InterviewFormat_INTERVIEW_FORMAT_UNSPECIFIED InterviewFormat = 0
	InterviewFormat_VIDEO                        InterviewFormat = 1
	InterviewFormat_PHONE                        InterviewFormat = 2
	InterviewFormat_ONSITE                       InterviewFormat = 3
)

// Enum value maps for InterviewFormat.
var (
	InterviewFormat_name = map[int32]string{
		0: "INTERVIEW_FORMAT_UNSPECIFIED",
		1: "VIDEO",
		2: "PHONE",
		3: "ONSITE",
	}
	InterviewFormat_value = map[string]int32{
		"INTERVIEW_FORMAT_UNSPECIFIED": 0,
		"VIDEO":                        1,
		"PHONE":                        2,
		"ONSITE":                       3,
	}
)

func (x InterviewFormat) Enum() *InterviewFormat {
	p := new(InterviewFormat)
	*p = x
	return p
}

func (x InterviewFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterviewFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (InterviewFormat) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x InterviewFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterviewFormat.Descriptor instead.
func (InterviewFormat) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

// InterviewStatus for interview state tracking
type InterviewStatus int32

const (
	InterviewStatus_INTERVIEW_STATUS_UNSPECIFIED InterviewStatus = 0
	InterviewStatus_PENDING                      InterviewStatus = 1
	InterviewStatus_CONFIRMED                    InterviewStatus = 2
	InterviewStatus_CANCELLED                    InterviewStatus = 3
	InterviewStatus_COMPLETED                    InterviewStatus = 4
)

// Enum value maps for InterviewStatus.
var (
	InterviewStatus_name = map[int32]string{
		0: "INTERVIEW_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "CONFIRMED",
		3: "CANCELLED",
		4: "COMPLETED",
	}
	InterviewStatus_value = map[string]int32{
		"INTERVIEW_STATUS_UNSPECIFIED": 0,
		"PENDING":                      1,
		"CONFIRMED":                    2,
		"CANCELLED":                    3,
		"COMPLETED":                    4,
	}
)

func (x InterviewStatus) Enum() *InterviewStatus {
	p := new(InterviewStatus)
	*p = x
	return p
}

func (x InterviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[4].Descriptor()
}

func (InterviewStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[4]
}

func (x InterviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterviewStatus.Descriptor instead.
func (InterviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

// OfferStatus for offer lifecycle
type OfferStatus int32

const (
	OfferStatus_OFFER_STATUS_UNSPECIFIED OfferStatus = 0
	OfferStatus_PENDING_ACCEPTANCE       OfferStatus = 1
	OfferStatus_ACCEPTED                 OfferStatus = 2
	OfferStatus_DECLINED                 OfferStatus = 3
	OfferStatus_EXPIRED                  OfferStatus = 4
)

// Enum value maps for OfferStatus.
var (
	OfferStatus_name = map[int32]string{
		0: "OFFER_STATUS_UNSPECIFIED",
		1: "PENDING_ACCEPTANCE",
		2: "ACCEPTED",
		3: "DECLINED",
		4: "EXPIRED",
	}
	OfferStatus_value = map[string]int32{
		"OFFER_STATUS_UNSPECIFIED": 0,
		"PENDING_ACCEPTANCE":       1,
		"ACCEPTED":                 2,
		"DECLINED":                 3,
		"EXPIRED":                  4,
	}
)

func (x OfferStatus) Enum() *OfferStatus {
	p := new(OfferStatus)
	*p = x
	return p
}

func (x OfferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[5].Descriptor()
}

func (OfferStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[5]
}

func (x OfferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfferStatus.Descriptor instead.
func (OfferStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

// MessageType for WebSocket frame dispatching
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_TEXT                     MessageType = 1
	MessageType_TOOL_CALL                MessageType = 2
	MessageType_TOOL_RESULT              MessageType = 3
	MessageType_STATE_CHANGE             MessageType = 4
	MessageType_MEMORY_UPDATE            MessageType = 5
	MessageType_HEARTBEAT                MessageType = 6
	MessageType_ERROR                    MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "TEXT",
		2: "TOOL_CALL",
		3: "TOOL_RESULT",
		4: "STATE_CHANGE",
		5: "MEMORY_UPDATE",
		6: "HEARTBEAT",
		7: "ERROR",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"TEXT":                     1,
		"TOOL_CALL":                2,
		"TOOL_RESULT":              3,
		"STATE_CHANGE":             4,
		"MEMORY_UPDATE":            5,
		"HEARTBEAT":                6,
		"ERROR":                    7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[6].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[6]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

// TextMessage is the core conversation unit between agents
type TextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          AgentRole              `protobuf:"varint,2,opt,name=role,proto3,enum=joblinker.AgentRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IntentType    string                 `protobuf:"bytes,4,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CacheKey      string                 `protobuf:"bytes,6,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TextMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextMessage) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

func (x *TextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextMessage) GetIntentType() string {
	if x != nil {
		return x.IntentType
	}
	return ""
}

func (x *TextMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TextMessage) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

// ToolCall represents a function invocation request
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	CacheKey      string                 `protobuf:"bytes,4,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCall) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

// ToolResult represents the result of a tool execution
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CacheKey      string                 `protobuf:"bytes,4,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ToolResult) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *ToolResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ToolResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StateChangeEvent notifies subscribers of FSM transitions
type StateChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	OldState      AgentState             `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=joblinker.AgentState" json:"old_state,omitempty"`
	NewState      AgentState             `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=joblinker.AgentState" json:"new_state,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeEvent) Reset() {
	*x = StateChangeEvent{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeEvent) ProtoMessage() {}

func (x *StateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeEvent.ProtoReflect.Descriptor instead.
func (*StateChangeEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StateChangeEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *StateChangeEvent) GetOldState() AgentState {
	if x != nil {
		return x.OldState
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *StateChangeEvent) GetNewState() AgentState {
	if x != nil {
		return x.NewState
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *StateChangeEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StateChangeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MemoryUpdate notifies of vector memory changes
type MemoryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	MemoryType    string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []float64              `protobuf:"fixed64,5,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryUpdate) Reset() {
	*x = MemoryUpdate{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryUpdate) ProtoMessage() {}

func (x *MemoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryUpdate.ProtoReflect.Descriptor instead.
func (*MemoryUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryUpdate) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MemoryUpdate) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemoryUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryUpdate) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *MemoryUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JobDetail describes a job posting
type JobDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SalaryMin          int64                  `protobuf:"varint,4,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax          int64                  `protobuf:"varint,5,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	Currency           string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Location           string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Skills             []string               `protobuf:"bytes,8,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceYearsMin int32                  `protobuf:"varint,9,opt,name=experience_years_min,json=experienceYearsMin,proto3" json:"experience_years_min,omitempty"`
	ExperienceYearsMax int32                  `protobuf:"varint,10,opt,name=experience_years_max,json=experienceYearsMax,proto3" json:"experience_years_max,omitempty"`
	PostedAt           int64                  `protobuf:"varint,11,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	Status             string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobDetail) Reset() {
	*x = JobDetail{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetail) ProtoMessage() {}

func (x *JobDetail) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetail.ProtoReflect.Descriptor instead.
func (*JobDetail) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *JobDetail) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobDetail) GetSalaryMin() int64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *JobDetail) GetSalaryMax() int64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *JobDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *JobDetail) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *JobDetail) GetExperienceYearsMin() int32 {
	if x != nil {
		return x.ExperienceYearsMin
	}
	return 0
}

func (x *JobDetail) GetExperienceYearsMax() int32 {
	if x != nil {
		return x.ExperienceYearsMax
	}
	return 0
}

func (x *JobDetail) GetPostedAt() int64 {
	if x != nil {
		return x.PostedAt
	}
	return 0
}

func (x *JobDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ResumeDetail describes a candidate resume
type ResumeDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ResumeId             string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	CandidateName        string                 `protobuf:"bytes,2,opt,name=candidate_name,json=candidateName,proto3" json:"candidate_name,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Skills               []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceYears      int32                  `protobuf:"varint,6,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	SalaryExpectationMin int64                  `protobuf:"varint,7,opt,name=salary_expectation_min,json=salaryExpectationMin,proto3" json:"salary_expectation_min,omitempty"`
	SalaryExpectationMax int64                  `protobuf:"varint,8,opt,name=salary_expectation_max,json=salaryExpectationMax,proto3" json:"salary_expectation_max,omitempty"`
	LocationPreference   string                 `protobuf:"bytes,9,opt,name=location_preference,json=locationPreference,proto3" json:"location_preference,omitempty"`
	Summary              string                 `protobuf:"bytes,10,opt,name=summary,proto3" json:"summary,omitempty"`
	UploadedAt           int64                  `protobuf:"varint,11,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResumeDetail) Reset() {
	*x = ResumeDetail{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDetail) ProtoMessage() {}

func (x *ResumeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDetail.ProtoReflect.Descriptor instead.
func (*ResumeDetail) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeDetail) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ResumeDetail) GetCandidateName() string {
	if x != nil {
		return x.CandidateName
	}
	return ""
}

func (x *ResumeDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResumeDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResumeDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeDetail) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *ResumeDetail) GetSalaryExpectationMin() int64 {
	if x != nil {
		return x.SalaryExpectationMin
	}
	return 0
}

func (x *ResumeDetail) GetSalaryExpectationMax() int64 {
	if x != nil {
		return x.SalaryExpectationMax
	}
	return 0
}

func (x *ResumeDetail) GetLocationPreference() string {
	if x != nil {
		return x.LocationPreference
	}
	return ""
}

func (x *ResumeDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeDetail) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

// InterviewInvitation is a scheduled interview
type InterviewInvitation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InterviewId     string                 `protobuf:"bytes,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	MatchId         string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ScheduledAt     int64                  `protobuf:"varint,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Format          InterviewFormat        `protobuf:"varint,5,opt,name=format,proto3,enum=joblinker.InterviewFormat" json:"format,omitempty"`
	LocationOrUrl   string                 `protobuf:"bytes,6,opt,name=location_or_url,json=locationOrUrl,proto3" json:"location_or_url,omitempty"`
	Status          InterviewStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=joblinker.InterviewStatus" json:"status,omitempty"`
	Notes           string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterviewInvitation) Reset() {
	*x = InterviewInvitation{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewInvitation) ProtoMessage() {}

func (x *InterviewInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewInvitation.ProtoReflect.Descriptor instead.
func (*InterviewInvitation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *InterviewInvitation) GetInterviewId() string {
	if x != nil {
		return x.InterviewId
	}
	return ""
}

func (x *InterviewInvitation) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *InterviewInvitation) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *InterviewInvitation) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *InterviewInvitation) GetFormat() InterviewFormat {
	if x != nil {
		return x.Format
	}
	return InterviewFormat_INTERVIEW_FORMAT_UNSPECIFIED
}

func (x *InterviewInvitation) GetLocationOrUrl() string {
	if x != nil {
		return x.LocationOrUrl
	}
	return ""
}

func (x *InterviewInvitation) GetStatus() InterviewStatus {
	if x != nil {
		return x.Status
	}
	return InterviewStatus_INTERVIEW_STATUS_UNSPECIFIED
}

func (x *InterviewInvitation) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// OfferDetail is a job offer
type OfferDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	SalaryAmount  int64                  `protobuf:"varint,3,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	StartDate     int64                  `protobuf:"varint,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Benefits      []string               `protobuf:"bytes,6,rep,name=benefits,proto3" json:"benefits,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        OfferStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=joblinker.OfferStatus" json:"status,omitempty"`
	Terms         string                 `protobuf:"bytes,9,opt,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferDetail) Reset() {
	*x = OfferDetail{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferDetail) ProtoMessage() {}

func (x *OfferDetail) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferDetail.ProtoReflect.Descriptor instead.
func (*OfferDetail) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *OfferDetail) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *OfferDetail) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *OfferDetail) GetSalaryAmount() int64 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *OfferDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OfferDetail) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *OfferDetail) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *OfferDetail) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *OfferDetail) GetStatus() OfferStatus {
	if x != nil {
		return x.Status
	}
	return OfferStatus_OFFER_STATUS_UNSPECIFIED
}

func (x *OfferDetail) GetTerms() string {
	if x != nil {
		return x.Terms
	}
	return ""
}

// QueueTask is a RabbitMQ task envelope
type QueueTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=joblinker.TaskPriority" json:"priority,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	RetryCount    uint32                 `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    uint32                 `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueTask) Reset() {
	*x = QueueTask{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueTask) ProtoMessage() {}

func (x *QueueTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueTask.ProtoReflect.Descriptor instead.
func (*QueueTask) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *QueueTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *QueueTask) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *QueueTask) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *QueueTask) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueueTask) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueueTask) GetMaxRetries() uint32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *QueueTask) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QueueTask) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *QueueTask) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// WebSocketFrame is the transport envelope for all WebSocket messages
type WebSocketFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=joblinker.MessageType" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SequenceNum   uint64                 `protobuf:"varint,3,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CacheKey      string                 `protobuf:"bytes,5,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketFrame) Reset() {
	*x = WebSocketFrame{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketFrame) ProtoMessage() {}

func (x *WebSocketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketFrame.ProtoReflect.Descriptor instead.
func (*WebSocketFrame) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *WebSocketFrame) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *WebSocketFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketFrame) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *WebSocketFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WebSocketFrame) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *WebSocketFrame) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *WebSocketFrame) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\tjoblinker\"\xbd\x01\n" +
	"\vTextMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04role\x18\x02 \x01(\x0e2\x14.joblinker.AgentRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vintent_type\x18\x04 \x01(\tR\n" +
	"intentType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcache_key\x18\x06 \x01(\tR\bcacheKey\"{\n" +
	"\bToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\fR\targuments\x12\x1b\n" +
	"\tcache_key\x18\x04 \x01(\tR\bcacheKey\"\xb5\x01\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\tcache_key\x18\x04 \x01(\tR\bcacheKey\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xcb\x01\n" +
	"\x10StateChangeEvent\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x122\n" +
	"\told_state\x18\x02 \x01(\x0e2\x15.joblinker.AgentStateR\boldState\x122\n" +
	"\tnew_state\x18\x03 \x01(\x0e2\x15.joblinker.AgentStateR\bnewState\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xbb\x01\n" +
	"\fMemoryUpdate\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x05 \x03(\x01R\tembedding\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x81\x03\n" +
	"\tJobDetail\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x04 \x01(\x03R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x05 \x01(\x03R\tsalaryMax\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\b \x03(\tR\x06skills\x120\n" +
	"\x14experience_years_min\x18\t \x01(\x05R\x12experienceYearsMin\x120\n" +
	"\x14experience_years_max\x18\n" +
	" \x01(\x05R\x12experienceYearsMax\x12\x1b\n" +
	"\tposted_at\x18\v \x01(\x03R\bpostedAt\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"\x99\x03\n" +
	"\fResumeDetail\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12%\n" +
	"\x0ecandidate_name\x18\x02 \x01(\tR\rcandidateName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12)\n" +
	"\x10experience_years\x18\x06 \x01(\x05R\x0fexperienceYears\x124\n" +
	"\x16salary_expectation_min\x18\a \x01(\x03R\x14salaryExpectationMin\x124\n" +
	"\x16salary_expectation_max\x18\b \x01(\x03R\x14salaryExpectationMax\x12/\n" +
	"\x13location_preference\x18\t \x01(\tR\x12locationPreference\x12\x18\n" +
	"\asummary\x18\n" +
	" \x01(\tR\asummary\x12\x1f\n" +
	"\vuploaded_at\x18\v \x01(\x03R\n" +
	"uploadedAt\"\xc7\x02\n" +
	"\x13InterviewInvitation\x12!\n" +
	"\finterview_id\x18\x01 \x01(\tR\vinterviewId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x12!\n" +
	"\fscheduled_at\x18\x03 \x01(\x03R\vscheduledAt\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x122\n" +
	"\x06format\x18\x05 \x01(\x0e2\x1a.joblinker.InterviewFormatR\x06format\x12&\n" +
	"\x0flocation_or_url\x18\x06 \x01(\tR\rlocationOrUrl\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.joblinker.InterviewStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\"\xa4\x02\n" +
	"\vOfferDetail\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x12#\n" +
	"\rsalary_amount\x18\x03 \x01(\x03R\fsalaryAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\x03R\tstartDate\x12\x1a\n" +
	"\bbenefits\x18\x06 \x03(\tR\bbenefits\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.joblinker.OfferStatusR\x06status\x12\x14\n" +
	"\x05terms\x18\t \x01(\tR\x05terms\"\xbb\x02\n" +
	"\tQueueTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x17.joblinker.TaskPriorityR\bpriority\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\rR\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\rR\n" +
	"maxRetries\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12!\n" +
	"\fscheduled_at\x18\b \x01(\x03R\vscheduledAt\x12%\n" +
	"\x0eschema_version\x18\t \x01(\rR\rschemaVersion\"\x91\x02\n" +
	"\x0eWebSocketFrame\x129\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x16.joblinker.MessageTypeR\vmessageType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fsequence_num\x18\x03 \x01(\x04R\vsequenceNum\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcache_key\x18\x05 \x01(\tR\bcacheKey\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\a \x01(\rR\rschemaVersion*B\n" +
	"\tAgentRole\x12\x1a\n" +
	"\x16AGENT_ROLE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SEEKER\x10\x01\x12\r\n" +
	"\tRECRUITER\x10\x02*\x92\x01\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\r\n" +
	"\tSEARCHING\x10\x02\x12\x0f\n" +
	"\vNEGOTIATING\x10\x03\x12\x10\n" +
	"\fINTERVIEWING\x10\x04\x12\x12\n" +
	"\x0eOFFER_RECEIVED\x10\x05\x12\t\n" +
	"\x05HIRED\x10\x06\x12\f\n" +
	"\bREJECTED\x10\a*Z\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*U\n" +
	"\x0fInterviewFormat\x12 \n" +
	"\x1cINTERVIEW_FORMAT_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05VIDEO\x10\x01\x12\t\n" +
	"\x05PHONE\x10\x02\x12\n" +
	"\n" +
	"\x06ONSITE\x10\x03*m\n" +
	"\x0fInterviewStatus\x12 \n" +
	"\x1cINTERVIEW_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tCONFIRMED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04*l\n" +
	"\vOfferStatus\x12\x1c\n" +
	"\x18OFFER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PENDING_ACCEPTANCE\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\f\n" +
	"\bDECLINED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04*\x94\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\x0f\n" +
	"\vTOOL_RESULT\x10\x03\x12\x10\n" +
	"\fSTATE_CHANGE\x10\x04\x12\x11\n" +
	"\rMEMORY_UPDATE\x10\x05\x12\r\n" +
	"\tHEARTBEAT\x10\x06\x12\t\n" +
	"\x05ERROR\x10\aB,\n" +
	"\x13com.joblinker.protoP\x01Z\x13joblinker/pkg/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_proto_goTypes = []any{
	(AgentRole)(0),              // 0: joblinker.AgentRole
	(AgentState)(0),             // 1: joblinker.AgentState
	(TaskPriority)(0),           // 2: joblinker.TaskPriority
	(InterviewFormat)(0),        // 3: joblinker.InterviewFormat
	(InterviewStatus)(0),        // 4: joblinker.InterviewStatus
	(OfferStatus)(0),            // 5: joblinker.OfferStatus
	(MessageType)(0),            // 6: joblinker.MessageType
	(*TextMessage)(nil),         // 7: joblinker.TextMessage
	(*ToolCall)(nil),            // 8: joblinker.ToolCall
	(*ToolResult)(nil),          // 9: joblinker.ToolResult
	(*StateChangeEvent)(nil),    // 10: joblinker.StateChangeEvent
	(*MemoryUpdate)(nil),        // 11: joblinker.MemoryUpdate
	(*JobDetail)(nil),           // 12: joblinker.JobDetail
	(*ResumeDetail)(nil),        // 13: joblinker.ResumeDetail
	(*InterviewInvitation)(nil), // 14: joblinker.InterviewInvitation
	(*OfferDetail)(nil),         // 15: joblinker.OfferDetail
	(*QueueTask)(nil),           // 16: joblinker.QueueTask
	(*WebSocketFrame)(nil),      // 17: joblinker.WebSocketFrame
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: joblinker.TextMessage.role:type_name -> joblinker.AgentRole
	1, // 1: joblinker.StateChangeEvent.old_state:type_name -> joblinker.AgentState
	1, // 2: joblinker.StateChangeEvent.new_state:type_name -> joblinker.AgentState
	3, // 3: joblinker.InterviewInvitation.format:type_name -> joblinker.InterviewFormat
	4, // 4: joblinker.InterviewInvitation.status:type_name -> joblinker.InterviewStatus
	5, // 5: joblinker.OfferDetail.status:type_name -> joblinker.OfferStatus
	2, // 6: joblinker.QueueTask.priority:type_name -> joblinker.TaskPriority
	6, // 7: joblinker.WebSocketFrame.message_type:type_name -> joblinker.MessageType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
