// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: agent.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "joblinker";

/** AgentRole represents the type of agent in the A2A recruitment system */
export enum AgentRole {
  AGENT_ROLE_UNSPECIFIED = 0,
  SEEKER = 1,
  RECRUITER = 2,
  UNRECOGNIZED = -1,
}

export function agentRoleFromJSON(object: any): AgentRole {
  switch (object) {
    case 0:
    case "AGENT_ROLE_UNSPECIFIED":
      return AgentRole.AGENT_ROLE_UNSPECIFIED;
    case 1:
    case "SEEKER":
      return AgentRole.SEEKER;
    case 2:
    case "RECRUITER":
      return AgentRole.RECRUITER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentRole.UNRECOGNIZED;
  }
}

export function agentRoleToJSON(object: AgentRole): string {
  switch (object) {
    case AgentRole.AGENT_ROLE_UNSPECIFIED:
      return "AGENT_ROLE_UNSPECIFIED";
    case AgentRole.SEEKER:
      return "SEEKER";
    case AgentRole.RECRUITER:
      return "RECRUITER";
    case AgentRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** AgentState represents the current state of an agent in the FSM */
export enum AgentState {
  AGENT_STATE_UNSPECIFIED = 0,
  IDLE = 1,
  SEARCHING = 2,
  NEGOTIATING = 3,
  INTERVIEWING = 4,
  OFFER_RECEIVED = 5,
  HIRED = 6,
  REJECTED = 7,
  UNRECOGNIZED = -1,
}

export function agentStateFromJSON(object: any): AgentState {
  switch (object) {
    case 0:
    case "AGENT_STATE_UNSPECIFIED":
      return AgentState.AGENT_STATE_UNSPECIFIED;
    case 1:
    case "IDLE":
      return AgentState.IDLE;
    case 2:
    case "SEARCHING":
      return AgentState.SEARCHING;
    case 3:
    case "NEGOTIATING":
      return AgentState.NEGOTIATING;
    case 4:
    case "INTERVIEWING":
      return AgentState.INTERVIEWING;
    case 5:
    case "OFFER_RECEIVED":
      return AgentState.OFFER_RECEIVED;
    case 6:
    case "HIRED":
      return AgentState.HIRED;
    case 7:
    case "REJECTED":
      return AgentState.REJECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentState.UNRECOGNIZED;
  }
}

export function agentStateToJSON(object: AgentState): string {
  switch (object) {
    case AgentState.AGENT_STATE_UNSPECIFIED:
      return "AGENT_STATE_UNSPECIFIED";
    case AgentState.IDLE:
      return "IDLE";
    case AgentState.SEARCHING:
      return "SEARCHING";
    case AgentState.NEGOTIATING:
      return "NEGOTIATING";
    case AgentState.INTERVIEWING:
      return "INTERVIEWING";
    case AgentState.OFFER_RECEIVED:
      return "OFFER_RECEIVED";
    case AgentState.HIRED:
      return "HIRED";
    case AgentState.REJECTED:
      return "REJECTED";
    case AgentState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** TaskPriority for RabbitMQ queue tasks */
export enum TaskPriority {
  TASK_PRIORITY_UNSPECIFIED = 0,
  LOW = 1,
  NORMAL = 2,
  HIGH = 3,
  CRITICAL = 4,
  UNRECOGNIZED = -1,
}

export function taskPriorityFromJSON(object: any): TaskPriority {
  switch (object) {
    case 0:
    case "TASK_PRIORITY_UNSPECIFIED":
      return TaskPriority.TASK_PRIORITY_UNSPECIFIED;
    case 1:
    case "LOW":
      return TaskPriority.LOW;
    case 2:
    case "NORMAL":
      return TaskPriority.NORMAL;
    case 3:
    case "HIGH":
      return TaskPriority.HIGH;
    case 4:
    case "CRITICAL":
      return TaskPriority.CRITICAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskPriority.UNRECOGNIZED;
  }
}

export function taskPriorityToJSON(object: TaskPriority): string {
  switch (object) {
    case TaskPriority.TASK_PRIORITY_UNSPECIFIED:
      return "TASK_PRIORITY_UNSPECIFIED";
    case TaskPriority.LOW:
      return "LOW";
    case TaskPriority.NORMAL:
      return "NORMAL";
    case TaskPriority.HIGH:
      return "HIGH";
    case TaskPriority.CRITICAL:
      return "CRITICAL";
    case TaskPriority.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** InterviewFormat for interview invitations */
export enum InterviewFormat {
  INTERVIEW_FORMAT_UNSPECIFIED = 0,
  VIDEO = 1,
  PHONE = 2,
  ONSITE = 3,
  UNRECOGNIZED = -1,
}

export function interviewFormatFromJSON(object: any): InterviewFormat {
  switch (object) {
    case 0:
    case "INTERVIEW_FORMAT_UNSPECIFIED":
      return InterviewFormat.INTERVIEW_FORMAT_UNSPECIFIED;
    case 1:
    case "VIDEO":
      return InterviewFormat.VIDEO;
    case 2:
    case "PHONE":
      return InterviewFormat.PHONE;
    case 3:
    case "ONSITE":
      return InterviewFormat.ONSITE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InterviewFormat.UNRECOGNIZED;
  }
}

export function interviewFormatToJSON(object: InterviewFormat): string {
  switch (object) {
    case InterviewFormat.INTERVIEW_FORMAT_UNSPECIFIED:
      return "INTERVIEW_FORMAT_UNSPECIFIED";
    case InterviewFormat.VIDEO:
      return "VIDEO";
    case InterviewFormat.PHONE:
      return "PHONE";
    case InterviewFormat.ONSITE:
      return "ONSITE";
    case InterviewFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** InterviewStatus for interview state tracking */
export enum InterviewStatus {
  INTERVIEW_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  CONFIRMED = 2,
  CANCELLED = 3,
  COMPLETED = 4,
  UNRECOGNIZED = -1,
}

export function interviewStatusFromJSON(object: any): InterviewStatus {
  switch (object) {
    case 0:
    case "INTERVIEW_STATUS_UNSPECIFIED":
      return InterviewStatus.INTERVIEW_STATUS_UNSPECIFIED;
    case 1:
    case "PENDING":
      return InterviewStatus.PENDING;
    case 2:
    case "CONFIRMED":
      return InterviewStatus.CONFIRMED;
    case 3:
    case "CANCELLED":
      return InterviewStatus.CANCELLED;
    case 4:
    case "COMPLETED":
      return InterviewStatus.COMPLETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InterviewStatus.UNRECOGNIZED;
  }
}

export function interviewStatusToJSON(object: InterviewStatus): string {
  switch (object) {
    case InterviewStatus.INTERVIEW_STATUS_UNSPECIFIED:
      return "INTERVIEW_STATUS_UNSPECIFIED";
    case InterviewStatus.PENDING:
      return "PENDING";
    case InterviewStatus.CONFIRMED:
      return "CONFIRMED";
    case InterviewStatus.CANCELLED:
      return "CANCELLED";
    case InterviewStatus.COMPLETED:
      return "COMPLETED";
    case InterviewStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** OfferStatus for offer lifecycle */
export enum OfferStatus {
  OFFER_STATUS_UNSPECIFIED = 0,
  PENDING_ACCEPTANCE = 1,
  ACCEPTED = 2,
  DECLINED = 3,
  EXPIRED = 4,
  UNRECOGNIZED = -1,
}

export function offerStatusFromJSON(object: any): OfferStatus {
  switch (object) {
    case 0:
    case "OFFER_STATUS_UNSPECIFIED":
      return OfferStatus.OFFER_STATUS_UNSPECIFIED;
    case 1:
    case "PENDING_ACCEPTANCE":
      return OfferStatus.PENDING_ACCEPTANCE;
    case 2:
    case "ACCEPTED":
      return OfferStatus.ACCEPTED;
    case 3:
    case "DECLINED":
      return OfferStatus.DECLINED;
    case 4:
    case "EXPIRED":
      return OfferStatus.EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OfferStatus.UNRECOGNIZED;
  }
}

export function offerStatusToJSON(object: OfferStatus): string {
  switch (object) {
    case OfferStatus.OFFER_STATUS_UNSPECIFIED:
      return "OFFER_STATUS_UNSPECIFIED";
    case OfferStatus.PENDING_ACCEPTANCE:
      return "PENDING_ACCEPTANCE";
    case OfferStatus.ACCEPTED:
      return "ACCEPTED";
    case OfferStatus.DECLINED:
      return "DECLINED";
    case OfferStatus.EXPIRED:
      return "EXPIRED";
    case OfferStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** MessageType for WebSocket frame dispatching */
export enum MessageType {
  MESSAGE_TYPE_UNSPECIFIED = 0,
  TEXT = 1,
  TOOL_CALL = 2,
  TOOL_RESULT = 3,
  STATE_CHANGE = 4,
  MEMORY_UPDATE = 5,
  HEARTBEAT = 6,
  ERROR = 7,
  UNRECOGNIZED = -1,
}

export function messageTypeFromJSON(object: any): MessageType {
  switch (object) {
    case 0:
    case "MESSAGE_TYPE_UNSPECIFIED":
      return MessageType.MESSAGE_TYPE_UNSPECIFIED;
    case 1:
    case "TEXT":
      return MessageType.TEXT;
    case 2:
    case "TOOL_CALL":
      return MessageType.TOOL_CALL;
    case 3:
    case "TOOL_RESULT":
      return MessageType.TOOL_RESULT;
    case 4:
    case "STATE_CHANGE":
      return MessageType.STATE_CHANGE;
    case 5:
    case "MEMORY_UPDATE":
      return MessageType.MEMORY_UPDATE;
    case 6:
    case "HEARTBEAT":
      return MessageType.HEARTBEAT;
    case 7:
    case "ERROR":
      return MessageType.ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageType.UNRECOGNIZED;
  }
}

export function messageTypeToJSON(object: MessageType): string {
  switch (object) {
    case MessageType.MESSAGE_TYPE_UNSPECIFIED:
      return "MESSAGE_TYPE_UNSPECIFIED";
    case MessageType.TEXT:
      return "TEXT";
    case MessageType.TOOL_CALL:
      return "TOOL_CALL";
    case MessageType.TOOL_RESULT:
      return "TOOL_RESULT";
    case MessageType.STATE_CHANGE:
      return "STATE_CHANGE";
    case MessageType.MEMORY_UPDATE:
      return "MEMORY_UPDATE";
    case MessageType.HEARTBEAT:
      return "HEARTBEAT";
    case MessageType.ERROR:
      return "ERROR";
    case MessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** TextMessage is the core conversation unit between agents */
export interface TextMessage {
  id: string;
  role: AgentRole;
  content: string;
  intentType: string;
  timestamp: number;
  cacheKey: string;
}

/** ToolCall represents a function invocation request */
export interface ToolCall {
  callId: string;
  toolName: string;
  arguments: Uint8Array;
  cacheKey: string;
}

/** ToolResult represents the result of a tool execution */
export interface ToolResult {
  callId: string;
  success: boolean;
  payload: Uint8Array;
  cacheKey: string;
  summary: string;
  errorMessage: string;
}

/** StateChangeEvent notifies subscribers of FSM transitions */
export interface StateChangeEvent {
  matchId: string;
  oldState: AgentState;
  newState: AgentState;
  reason: string;
  timestamp: number;
}

/** MemoryUpdate notifies of vector memory changes */
export interface MemoryUpdate {
  memoryId: string;
  memoryType: string;
  userId: string;
  content: string;
  embedding: number[];
  timestamp: number;
}

/** JobDetail describes a job posting */
export interface JobDetail {
  jobId: string;
  title: string;
  description: string;
  salaryMin: number;
  salaryMax: number;
  currency: string;
  location: string;
  skills: string[];
  experienceYearsMin: number;
  experienceYearsMax: number;
  postedAt: number;
  status: string;
}

/** ResumeDetail describes a candidate resume */
export interface ResumeDetail {
  resumeId: string;
  candidateName: string;
  email: string;
  phone: string;
  skills: string[];
  experienceYears: number;
  salaryExpectationMin: number;
  salaryExpectationMax: number;
  locationPreference: string;
  summary: string;
  uploadedAt: number;
}

/** InterviewInvitation is a scheduled interview */
export interface InterviewInvitation {
  interviewId: string;
  matchId: string;
  scheduledAt: number;
  durationMinutes: number;
  format: InterviewFormat;
  locationOrUrl: string;
  status: InterviewStatus;
  notes: string;
}

/** OfferDetail is a job offer */
export interface OfferDetail {
  offerId: string;
  matchId: string;
  salaryAmount: number;
  currency: string;
  startDate: number;
  benefits: string[];
  expiresAt: number;
  status: OfferStatus;
  terms: string;
}

/** QueueTask is a RabbitMQ task envelope */
export interface QueueTask {
  taskId: string;
  taskType: string;
  priority: TaskPriority;
  payload: Uint8Array;
  retryCount: number;
  maxRetries: number;
  createdAt: number;
  scheduledAt: number;
  schemaVersion: number;
}

/** WebSocketFrame is the transport envelope for all WebSocket messages */
export interface WebSocketFrame {
  messageType: MessageType;
  payload: Uint8Array;
  sequenceNum: number;
  timestamp: number;
  cacheKey: string;
  correlationId: string;
  schemaVersion: number;
}

function createBaseTextMessage(): TextMessage {
  return { id: "", role: 0, content: "", intentType: "", timestamp: 0, cacheKey: "" };
}

export const TextMessage: MessageFns<TextMessage> = {
  encode(message: TextMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    if (message.intentType !== "") {
      writer.uint32(34).string(message.intentType);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    if (message.cacheKey !== "") {
      writer.uint32(50).string(message.cacheKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.intentType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cacheKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TextMessage {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      role: isSet(object.role) ? agentRoleFromJSON(object.role) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      intentType: isSet(object.intentType)
        ? globalThis.String(object.intentType)
        : isSet(object.intent_type)
        ? globalThis.String(object.intent_type)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      cacheKey: isSet(object.cacheKey)
        ? globalThis.String(object.cacheKey)
        : isSet(object.cache_key)
        ? globalThis.String(object.cache_key)
        : "",
    };
  },

  toJSON(message: TextMessage): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.role !== 0) {
      obj.role = agentRoleToJSON(message.role);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.intentType !== "") {
      obj.intentType = message.intentType;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.cacheKey !== "") {
      obj.cacheKey = message.cacheKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TextMessage>, I>>(base?: I): TextMessage {
    return TextMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TextMessage>, I>>(object: I): TextMessage {
    const message = createBaseTextMessage();
    message.id = object.id ?? "";
    message.role = object.role ?? 0;
    message.content = object.content ?? "";
    message.intentType = object.intentType ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.cacheKey = object.cacheKey ?? "";
    return message;
  },
};

function createBaseToolCall(): ToolCall {
  return { callId: "", toolName: "", arguments: new Uint8Array(0), cacheKey: "" };
}

export const ToolCall: MessageFns<ToolCall> = {
  encode(message: ToolCall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.toolName !== "") {
      writer.uint32(18).string(message.toolName);
    }
    if (message.arguments.length !== 0) {
      writer.uint32(26).bytes(message.arguments);
    }
    if (message.cacheKey !== "") {
      writer.uint32(34).string(message.cacheKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.arguments = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cacheKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCall {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      toolName: isSet(object.toolName)
        ? globalThis.String(object.toolName)
        : isSet(object.tool_name)
        ? globalThis.String(object.tool_name)
        : "",
      arguments: isSet(object.arguments) ? bytesFromBase64(object.arguments) : new Uint8Array(0),
      cacheKey: isSet(object.cacheKey)
        ? globalThis.String(object.cacheKey)
        : isSet(object.cache_key)
        ? globalThis.String(object.cache_key)
        : "",
    };
  },

  toJSON(message: ToolCall): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.arguments.length !== 0) {
      obj.arguments = base64FromBytes(message.arguments);
    }
    if (message.cacheKey !== "") {
      obj.cacheKey = message.cacheKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCall>, I>>(base?: I): ToolCall {
    return ToolCall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCall>, I>>(object: I): ToolCall {
    const message = createBaseToolCall();
    message.callId = object.callId ?? "";
    message.toolName = object.toolName ?? "";
    message.arguments = object.arguments ?? new Uint8Array(0);
    message.cacheKey = object.cacheKey ?? "";
    return message;
  },
};

function createBaseToolResult(): ToolResult {
  return { callId: "", success: false, payload: new Uint8Array(0), cacheKey: "", summary: "", errorMessage: "" };
}

export const ToolResult: MessageFns<ToolResult> = {
  encode(message: ToolResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    if (message.cacheKey !== "") {
      writer.uint32(34).string(message.cacheKey);
    }
    if (message.summary !== "") {
      writer.uint32(42).string(message.summary);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cacheKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolResult {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      cacheKey: isSet(object.cacheKey)
        ? globalThis.String(object.cacheKey)
        : isSet(object.cache_key)
        ? globalThis.String(object.cache_key)
        : "",
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: ToolResult): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.cacheKey !== "") {
      obj.cacheKey = message.cacheKey;
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolResult>, I>>(base?: I): ToolResult {
    return ToolResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolResult>, I>>(object: I): ToolResult {
    const message = createBaseToolResult();
    message.callId = object.callId ?? "";
    message.success = object.success ?? false;
    message.payload = object.payload ?? new Uint8Array(0);
    message.cacheKey = object.cacheKey ?? "";
    message.summary = object.summary ?? "";
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseStateChangeEvent(): StateChangeEvent {
  return { matchId: "", oldState: 0, newState: 0, reason: "", timestamp: 0 };
}

export const StateChangeEvent: MessageFns<StateChangeEvent> = {
  encode(message: StateChangeEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.matchId !== "") {
      writer.uint32(10).string(message.matchId);
    }
    if (message.oldState !== 0) {
      writer.uint32(16).int32(message.oldState);
    }
    if (message.newState !== 0) {
      writer.uint32(24).int32(message.newState);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateChangeEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateChangeEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.matchId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.oldState = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.newState = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateChangeEvent {
    return {
      matchId: isSet(object.matchId)
        ? globalThis.String(object.matchId)
        : isSet(object.match_id)
        ? globalThis.String(object.match_id)
        : "",
      oldState: isSet(object.oldState)
        ? agentStateFromJSON(object.oldState)
        : isSet(object.old_state)
        ? agentStateFromJSON(object.old_state)
        : 0,
      newState: isSet(object.newState)
        ? agentStateFromJSON(object.newState)
        : isSet(object.new_state)
        ? agentStateFromJSON(object.new_state)
        : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: StateChangeEvent): unknown {
    const obj: any = {};
    if (message.matchId !== "") {
      obj.matchId = message.matchId;
    }
    if (message.oldState !== 0) {
      obj.oldState = agentStateToJSON(message.oldState);
    }
    if (message.newState !== 0) {
      obj.newState = agentStateToJSON(message.newState);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateChangeEvent>, I>>(base?: I): StateChangeEvent {
    return StateChangeEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateChangeEvent>, I>>(object: I): StateChangeEvent {
    const message = createBaseStateChangeEvent();
    message.matchId = object.matchId ?? "";
    message.oldState = object.oldState ?? 0;
    message.newState = object.newState ?? 0;
    message.reason = object.reason ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseMemoryUpdate(): MemoryUpdate {
  return { memoryId: "", memoryType: "", userId: "", content: "", embedding: [], timestamp: 0 };
}

export const MemoryUpdate: MessageFns<MemoryUpdate> = {
  encode(message: MemoryUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memoryId !== "") {
      writer.uint32(10).string(message.memoryId);
    }
    if (message.memoryType !== "") {
      writer.uint32(18).string(message.memoryType);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    writer.uint32(42).fork();
    for (const v of message.embedding) {
      writer.double(v);
    }
    writer.join();
    if (message.timestamp !== 0) {
      writer.uint32(48).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemoryUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemoryUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memoryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memoryType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag === 41) {
            message.embedding.push(reader.double());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.embedding.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemoryUpdate {
    return {
      memoryId: isSet(object.memoryId)
        ? globalThis.String(object.memoryId)
        : isSet(object.memory_id)
        ? globalThis.String(object.memory_id)
        : "",
      memoryType: isSet(object.memoryType)
        ? globalThis.String(object.memoryType)
        : isSet(object.memory_type)
        ? globalThis.String(object.memory_type)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      embedding: globalThis.Array.isArray(object?.embedding)
        ? object.embedding.map((e: any) => globalThis.Number(e))
        : [],
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: MemoryUpdate): unknown {
    const obj: any = {};
    if (message.memoryId !== "") {
      obj.memoryId = message.memoryId;
    }
    if (message.memoryType !== "") {
      obj.memoryType = message.memoryType;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.embedding?.length) {
      obj.embedding = message.embedding;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemoryUpdate>, I>>(base?: I): MemoryUpdate {
    return MemoryUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemoryUpdate>, I>>(object: I): MemoryUpdate {
    const message = createBaseMemoryUpdate();
    message.memoryId = object.memoryId ?? "";
    message.memoryType = object.memoryType ?? "";
    message.userId = object.userId ?? "";
    message.content = object.content ?? "";
    message.embedding = object.embedding?.map((e) => e) || [];
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseJobDetail(): JobDetail {
  return {
    jobId: "",
    title: "",
    description: "",
    salaryMin: 0,
    salaryMax: 0,
    currency: "",
    location: "",
    skills: [],
    experienceYearsMin: 0,
    experienceYearsMax: 0,
    postedAt: 0,
    status: "",
  };
}

export const JobDetail: MessageFns<JobDetail> = {
  encode(message: JobDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.salaryMin !== 0) {
      writer.uint32(32).int64(message.salaryMin);
    }
    if (message.salaryMax !== 0) {
      writer.uint32(40).int64(message.salaryMax);
    }
    if (message.currency !== "") {
      writer.uint32(50).string(message.currency);
    }
    if (message.location !== "") {
      writer.uint32(58).string(message.location);
    }
    for (const v of message.skills) {
      writer.uint32(66).string(v!);
    }
    if (message.experienceYearsMin !== 0) {
      writer.uint32(72).int32(message.experienceYearsMin);
    }
    if (message.experienceYearsMax !== 0) {
      writer.uint32(80).int32(message.experienceYearsMax);
    }
    if (message.postedAt !== 0) {
      writer.uint32(88).int64(message.postedAt);
    }
    if (message.status !== "") {
      writer.uint32(98).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.salaryMin = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.salaryMax = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.skills.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.experienceYearsMin = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.experienceYearsMax = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.postedAt = longToNumber(reader.int64());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobDetail {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      salaryMin: isSet(object.salaryMin)
        ? globalThis.Number(object.salaryMin)
        : isSet(object.salary_min)
        ? globalThis.Number(object.salary_min)
        : 0,
      salaryMax: isSet(object.salaryMax)
        ? globalThis.Number(object.salaryMax)
        : isSet(object.salary_max)
        ? globalThis.Number(object.salary_max)
        : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      skills: globalThis.Array.isArray(object?.skills) ? object.skills.map((e: any) => globalThis.String(e)) : [],
      experienceYearsMin: isSet(object.experienceYearsMin)
        ? globalThis.Number(object.experienceYearsMin)
        : isSet(object.experience_years_min)
        ? globalThis.Number(object.experience_years_min)
        : 0,
      experienceYearsMax: isSet(object.experienceYearsMax)
        ? globalThis.Number(object.experienceYearsMax)
        : isSet(object.experience_years_max)
        ? globalThis.Number(object.experience_years_max)
        : 0,
      postedAt: isSet(object.postedAt)
        ? globalThis.Number(object.postedAt)
        : isSet(object.posted_at)
        ? globalThis.Number(object.posted_at)
        : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: JobDetail): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.salaryMin !== 0) {
      obj.salaryMin = Math.round(message.salaryMin);
    }
    if (message.salaryMax !== 0) {
      obj.salaryMax = Math.round(message.salaryMax);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.skills?.length) {
      obj.skills = message.skills;
    }
    if (message.experienceYearsMin !== 0) {
      obj.experienceYearsMin = Math.round(message.experienceYearsMin);
    }
    if (message.experienceYearsMax !== 0) {
      obj.experienceYearsMax = Math.round(message.experienceYearsMax);
    }
    if (message.postedAt !== 0) {
      obj.postedAt = Math.round(message.postedAt);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobDetail>, I>>(base?: I): JobDetail {
    return JobDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobDetail>, I>>(object: I): JobDetail {
    const message = createBaseJobDetail();
    message.jobId = object.jobId ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.salaryMin = object.salaryMin ?? 0;
    message.salaryMax = object.salaryMax ?? 0;
    message.currency = object.currency ?? "";
    message.location = object.location ?? "";
    message.skills = object.skills?.map((e) => e) || [];
    message.experienceYearsMin = object.experienceYearsMin ?? 0;
    message.experienceYearsMax = object.experienceYearsMax ?? 0;
    message.postedAt = object.postedAt ?? 0;
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseResumeDetail(): ResumeDetail {
  return {
    resumeId: "",
    candidateName: "",
    email: "",
    phone: "",
    skills: [],
    experienceYears: 0,
    salaryExpectationMin: 0,
    salaryExpectationMax: 0,
    locationPreference: "",
    summary: "",
    uploadedAt: 0,
  };
}

export const ResumeDetail: MessageFns<ResumeDetail> = {
  encode(message: ResumeDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resumeId !== "") {
      writer.uint32(10).string(message.resumeId);
    }
    if (message.candidateName !== "") {
      writer.uint32(18).string(message.candidateName);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.phone !== "") {
      writer.uint32(34).string(message.phone);
    }
    for (const v of message.skills) {
      writer.uint32(42).string(v!);
    }
    if (message.experienceYears !== 0) {
      writer.uint32(48).int32(message.experienceYears);
    }
    if (message.salaryExpectationMin !== 0) {
      writer.uint32(56).int64(message.salaryExpectationMin);
    }
    if (message.salaryExpectationMax !== 0) {
      writer.uint32(64).int64(message.salaryExpectationMax);
    }
    if (message.locationPreference !== "") {
      writer.uint32(74).string(message.locationPreference);
    }
    if (message.summary !== "") {
      writer.uint32(82).string(message.summary);
    }
    if (message.uploadedAt !== 0) {
      writer.uint32(88).int64(message.uploadedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResumeDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResumeDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidateName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.skills.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.experienceYears = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.salaryExpectationMin = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.salaryExpectationMax = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.locationPreference = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.uploadedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResumeDetail {
    return {
      resumeId: isSet(object.resumeId)
        ? globalThis.String(object.resumeId)
        : isSet(object.resume_id)
        ? globalThis.String(object.resume_id)
        : "",
      candidateName: isSet(object.candidateName)
        ? globalThis.String(object.candidateName)
        : isSet(object.candidate_name)
        ? globalThis.String(object.candidate_name)
        : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      skills: globalThis.Array.isArray(object?.skills) ? object.skills.map((e: any) => globalThis.String(e)) : [],
      experienceYears: isSet(object.experienceYears)
        ? globalThis.Number(object.experienceYears)
        : isSet(object.experience_years)
        ? globalThis.Number(object.experience_years)
        : 0,
      salaryExpectationMin: isSet(object.salaryExpectationMin)
        ? globalThis.Number(object.salaryExpectationMin)
        : isSet(object.salary_expectation_min)
        ? globalThis.Number(object.salary_expectation_min)
        : 0,
      salaryExpectationMax: isSet(object.salaryExpectationMax)
        ? globalThis.Number(object.salaryExpectationMax)
        : isSet(object.salary_expectation_max)
        ? globalThis.Number(object.salary_expectation_max)
        : 0,
      locationPreference: isSet(object.locationPreference)
        ? globalThis.String(object.locationPreference)
        : isSet(object.location_preference)
        ? globalThis.String(object.location_preference)
        : "",
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
      uploadedAt: isSet(object.uploadedAt)
        ? globalThis.Number(object.uploadedAt)
        : isSet(object.uploaded_at)
        ? globalThis.Number(object.uploaded_at)
        : 0,
    };
  },

  toJSON(message: ResumeDetail): unknown {
    const obj: any = {};
    if (message.resumeId !== "") {
      obj.resumeId = message.resumeId;
    }
    if (message.candidateName !== "") {
      obj.candidateName = message.candidateName;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.skills?.length) {
      obj.skills = message.skills;
    }
    if (message.experienceYears !== 0) {
      obj.experienceYears = Math.round(message.experienceYears);
    }
    if (message.salaryExpectationMin !== 0) {
      obj.salaryExpectationMin = Math.round(message.salaryExpectationMin);
    }
    if (message.salaryExpectationMax !== 0) {
      obj.salaryExpectationMax = Math.round(message.salaryExpectationMax);
    }
    if (message.locationPreference !== "") {
      obj.locationPreference = message.locationPreference;
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    if (message.uploadedAt !== 0) {
      obj.uploadedAt = Math.round(message.uploadedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResumeDetail>, I>>(base?: I): ResumeDetail {
    return ResumeDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResumeDetail>, I>>(object: I): ResumeDetail {
    const message = createBaseResumeDetail();
    message.resumeId = object.resumeId ?? "";
    message.candidateName = object.candidateName ?? "";
    message.email = object.email ?? "";
    message.phone = object.phone ?? "";
    message.skills = object.skills?.map((e) => e) || [];
    message.experienceYears = object.experienceYears ?? 0;
    message.salaryExpectationMin = object.salaryExpectationMin ?? 0;
    message.salaryExpectationMax = object.salaryExpectationMax ?? 0;
    message.locationPreference = object.locationPreference ?? "";
    message.summary = object.summary ?? "";
    message.uploadedAt = object.uploadedAt ?? 0;
    return message;
  },
};

function createBaseInterviewInvitation(): InterviewInvitation {
  return {
    interviewId: "",
    matchId: "",
    scheduledAt: 0,
    durationMinutes: 0,
    format: 0,
    locationOrUrl: "",
    status: 0,
    notes: "",
  };
}

export const InterviewInvitation: MessageFns<InterviewInvitation> = {
  encode(message: InterviewInvitation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.interviewId !== "") {
      writer.uint32(10).string(message.interviewId);
    }
    if (message.matchId !== "") {
      writer.uint32(18).string(message.matchId);
    }
    if (message.scheduledAt !== 0) {
      writer.uint32(24).int64(message.scheduledAt);
    }
    if (message.durationMinutes !== 0) {
      writer.uint32(32).int32(message.durationMinutes);
    }
    if (message.format !== 0) {
      writer.uint32(40).int32(message.format);
    }
    if (message.locationOrUrl !== "") {
      writer.uint32(50).string(message.locationOrUrl);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.notes !== "") {
      writer.uint32(66).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InterviewInvitation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInterviewInvitation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.interviewId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.matchId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.scheduledAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationMinutes = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.format = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.locationOrUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InterviewInvitation {
    return {
      interviewId: isSet(object.interviewId)
        ? globalThis.String(object.interviewId)
        : isSet(object.interview_id)
        ? globalThis.String(object.interview_id)
        : "",
      matchId: isSet(object.matchId)
        ? globalThis.String(object.matchId)
        : isSet(object.match_id)
        ? globalThis.String(object.match_id)
        : "",
      scheduledAt: isSet(object.scheduledAt)
        ? globalThis.Number(object.scheduledAt)
        : isSet(object.scheduled_at)
        ? globalThis.Number(object.scheduled_at)
        : 0,
      durationMinutes: isSet(object.durationMinutes)
        ? globalThis.Number(object.durationMinutes)
        : isSet(object.duration_minutes)
        ? globalThis.Number(object.duration_minutes)
        : 0,
      format: isSet(object.format) ? interviewFormatFromJSON(object.format) : 0,
      locationOrUrl: isSet(object.locationOrUrl)
        ? globalThis.String(object.locationOrUrl)
        : isSet(object.location_or_url)
        ? globalThis.String(object.location_or_url)
        : "",
      status: isSet(object.status) ? interviewStatusFromJSON(object.status) : 0,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
    };
  },

  toJSON(message: InterviewInvitation): unknown {
    const obj: any = {};
    if (message.interviewId !== "") {
      obj.interviewId = message.interviewId;
    }
    if (message.matchId !== "") {
      obj.matchId = message.matchId;
    }
    if (message.scheduledAt !== 0) {
      obj.scheduledAt = Math.round(message.scheduledAt);
    }
    if (message.durationMinutes !== 0) {
      obj.durationMinutes = Math.round(message.durationMinutes);
    }
    if (message.format !== 0) {
      obj.format = interviewFormatToJSON(message.format);
    }
    if (message.locationOrUrl !== "") {
      obj.locationOrUrl = message.locationOrUrl;
    }
    if (message.status !== 0) {
      obj.status = interviewStatusToJSON(message.status);
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InterviewInvitation>, I>>(base?: I): InterviewInvitation {
    return InterviewInvitation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InterviewInvitation>, I>>(object: I): InterviewInvitation {
    const message = createBaseInterviewInvitation();
    message.interviewId = object.interviewId ?? "";
    message.matchId = object.matchId ?? "";
    message.scheduledAt = object.scheduledAt ?? 0;
    message.durationMinutes = object.durationMinutes ?? 0;
    message.format = object.format ?? 0;
    message.locationOrUrl = object.locationOrUrl ?? "";
    message.status = object.status ?? 0;
    message.notes = object.notes ?? "";
    return message;
  },
};

function createBaseOfferDetail(): OfferDetail {
  return {
    offerId: "",
    matchId: "",
    salaryAmount: 0,
    currency: "",
    startDate: 0,
    benefits: [],
    expiresAt: 0,
    status: 0,
    terms: "",
  };
}

export const OfferDetail: MessageFns<OfferDetail> = {
  encode(message: OfferDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.offerId !== "") {
      writer.uint32(10).string(message.offerId);
    }
    if (message.matchId !== "") {
      writer.uint32(18).string(message.matchId);
    }
    if (message.salaryAmount !== 0) {
      writer.uint32(24).int64(message.salaryAmount);
    }
    if (message.currency !== "") {
      writer.uint32(34).string(message.currency);
    }
    if (message.startDate !== 0) {
      writer.uint32(40).int64(message.startDate);
    }
    for (const v of message.benefits) {
      writer.uint32(50).string(v!);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(56).int64(message.expiresAt);
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.terms !== "") {
      writer.uint32(74).string(message.terms);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OfferDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOfferDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.offerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.matchId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.salaryAmount = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startDate = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.benefits.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.terms = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OfferDetail {
    return {
      offerId: isSet(object.offerId)
        ? globalThis.String(object.offerId)
        : isSet(object.offer_id)
        ? globalThis.String(object.offer_id)
        : "",
      matchId: isSet(object.matchId)
        ? globalThis.String(object.matchId)
        : isSet(object.match_id)
        ? globalThis.String(object.match_id)
        : "",
      salaryAmount: isSet(object.salaryAmount)
        ? globalThis.Number(object.salaryAmount)
        : isSet(object.salary_amount)
        ? globalThis.Number(object.salary_amount)
        : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      startDate: isSet(object.startDate)
        ? globalThis.Number(object.startDate)
        : isSet(object.start_date)
        ? globalThis.Number(object.start_date)
        : 0,
      benefits: globalThis.Array.isArray(object?.benefits)
        ? object.benefits.map((e: any) => globalThis.String(e))
        : [],
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      status: isSet(object.status) ? offerStatusFromJSON(object.status) : 0,
      terms: isSet(object.terms) ? globalThis.String(object.terms) : "",
    };
  },

  toJSON(message: OfferDetail): unknown {
    const obj: any = {};
    if (message.offerId !== "") {
      obj.offerId = message.offerId;
    }
    if (message.matchId !== "") {
      obj.matchId = message.matchId;
    }
    if (message.salaryAmount !== 0) {
      obj.salaryAmount = Math.round(message.salaryAmount);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.startDate !== 0) {
      obj.startDate = Math.round(message.startDate);
    }
    if (message.benefits?.length) {
      obj.benefits = message.benefits;
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.status !== 0) {
      obj.status = offerStatusToJSON(message.status);
    }
    if (message.terms !== "") {
      obj.terms = message.terms;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OfferDetail>, I>>(base?: I): OfferDetail {
    return OfferDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OfferDetail>, I>>(object: I): OfferDetail {
    const message = createBaseOfferDetail();
    message.offerId = object.offerId ?? "";
    message.matchId = object.matchId ?? "";
    message.salaryAmount = object.salaryAmount ?? 0;
    message.currency = object.currency ?? "";
    message.startDate = object.startDate ?? 0;
    message.benefits = object.benefits?.map((e) => e) || [];
    message.expiresAt = object.expiresAt ?? 0;
    message.status = object.status ?? 0;
    message.terms = object.terms ?? "";
    return message;
  },
};

function createBaseQueueTask(): QueueTask {
  return {
    taskId: "",
    taskType: "",
    priority: 0,
    payload: new Uint8Array(0),
    retryCount: 0,
    maxRetries: 0,
    createdAt: 0,
    scheduledAt: 0,
    schemaVersion: 0,
  };
}

export const QueueTask: MessageFns<QueueTask> = {
  encode(message: QueueTask, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.taskType !== "") {
      writer.uint32(18).string(message.taskType);
    }
    if (message.priority !== 0) {
      writer.uint32(24).int32(message.priority);
    }
    if (message.payload.length !== 0) {
      writer.uint32(34).bytes(message.payload);
    }
    if (message.retryCount !== 0) {
      writer.uint32(40).uint32(message.retryCount);
    }
    if (message.maxRetries !== 0) {
      writer.uint32(48).uint32(message.maxRetries);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).int64(message.createdAt);
    }
    if (message.scheduledAt !== 0) {
      writer.uint32(64).int64(message.scheduledAt);
    }
    if (message.schemaVersion !== 0) {
      writer.uint32(72).uint32(message.schemaVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueTask {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.taskType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priority = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retryCount = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxRetries = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.scheduledAt = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueueTask {
    return {
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      taskType: isSet(object.taskType)
        ? globalThis.String(object.taskType)
        : isSet(object.task_type)
        ? globalThis.String(object.task_type)
        : "",
      priority: isSet(object.priority) ? taskPriorityFromJSON(object.priority) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      retryCount: isSet(object.retryCount)
        ? globalThis.Number(object.retryCount)
        : isSet(object.retry_count)
        ? globalThis.Number(object.retry_count)
        : 0,
      maxRetries: isSet(object.maxRetries)
        ? globalThis.Number(object.maxRetries)
        : isSet(object.max_retries)
        ? globalThis.Number(object.max_retries)
        : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      scheduledAt: isSet(object.scheduledAt)
        ? globalThis.Number(object.scheduledAt)
        : isSet(object.scheduled_at)
        ? globalThis.Number(object.scheduled_at)
        : 0,
      schemaVersion: isSet(object.schemaVersion)
        ? globalThis.Number(object.schemaVersion)
        : isSet(object.schema_version)
        ? globalThis.Number(object.schema_version)
        : 0,
    };
  },

  toJSON(message: QueueTask): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.taskType !== "") {
      obj.taskType = message.taskType;
    }
    if (message.priority !== 0) {
      obj.priority = taskPriorityToJSON(message.priority);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.retryCount !== 0) {
      obj.retryCount = Math.round(message.retryCount);
    }
    if (message.maxRetries !== 0) {
      obj.maxRetries = Math.round(message.maxRetries);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.scheduledAt !== 0) {
      obj.scheduledAt = Math.round(message.scheduledAt);
    }
    if (message.schemaVersion !== 0) {
      obj.schemaVersion = Math.round(message.schemaVersion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueTask>, I>>(base?: I): QueueTask {
    return QueueTask.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueTask>, I>>(object: I): QueueTask {
    const message = createBaseQueueTask();
    message.taskId = object.taskId ?? "";
    message.taskType = object.taskType ?? "";
    message.priority = object.priority ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    message.retryCount = object.retryCount ?? 0;
    message.maxRetries = object.maxRetries ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.scheduledAt = object.scheduledAt ?? 0;
    message.schemaVersion = object.schemaVersion ?? 0;
    return message;
  },
};

function createBaseWebSocketFrame(): WebSocketFrame {
  return {
    messageType: 0,
    payload: new Uint8Array(0),
    sequenceNum: 0,
    timestamp: 0,
    cacheKey: "",
    correlationId: "",
    schemaVersion: 0,
  };
}

export const WebSocketFrame: MessageFns<WebSocketFrame> = {
  encode(message: WebSocketFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.sequenceNum !== 0) {
      writer.uint32(24).uint64(message.sequenceNum);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    if (message.cacheKey !== "") {
      writer.uint32(42).string(message.cacheKey);
    }
    if (message.correlationId !== "") {
      writer.uint32(50).string(message.correlationId);
    }
    if (message.schemaVersion !== 0) {
      writer.uint32(56).uint32(message.schemaVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebSocketFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebSocketFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sequenceNum = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cacheKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebSocketFrame {
    return {
      messageType: isSet(object.messageType)
        ? messageTypeFromJSON(object.messageType)
        : isSet(object.message_type)
        ? messageTypeFromJSON(object.message_type)
        : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      sequenceNum: isSet(object.sequenceNum)
        ? globalThis.Number(object.sequenceNum)
        : isSet(object.sequence_num)
        ? globalThis.Number(object.sequence_num)
        : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      cacheKey: isSet(object.cacheKey)
        ? globalThis.String(object.cacheKey)
        : isSet(object.cache_key)
        ? globalThis.String(object.cache_key)
        : "",
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      schemaVersion: isSet(object.schemaVersion)
        ? globalThis.Number(object.schemaVersion)
        : isSet(object.schema_version)
        ? globalThis.Number(object.schema_version)
        : 0,
    };
  },

  toJSON(message: WebSocketFrame): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.sequenceNum !== 0) {
      obj.sequenceNum = Math.round(message.sequenceNum);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.cacheKey !== "") {
      obj.cacheKey = message.cacheKey;
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.schemaVersion !== 0) {
      obj.schemaVersion = Math.round(message.schemaVersion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebSocketFrame>, I>>(base?: I): WebSocketFrame {
    return WebSocketFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebSocketFrame>, I>>(object: I): WebSocketFrame {
    const message = createBaseWebSocketFrame();
    message.messageType = object.messageType ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    message.sequenceNum = object.sequenceNum ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.cacheKey = object.cacheKey ?? "";
    message.correlationId = object.correlationId ?? "";
    message.schemaVersion = object.schemaVersion ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
